name: Question
description: Ask a generic question on the project
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this question!
  - type: textarea
    id: about
    attributes:
      label: What would you like to ask?
      description: describe in detail your question
      placeholder: Ask us anything
      value: "Ask us anything!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you have read our [Project Guidelines](https://confluence.internal.salesforce.com/display/PSE/DRAFT+-+Internal+asset+initiative)
      options:
        - label: I confirm I have read the Project Guidelines
          required: true